dofile_once("data/scripts/perks/perklua")


BonusPerks = {
    
}

MutantPerks = {

}



local vanilla_bonuses = {
    BREATH_UNDERWATER =             11,
    HOVER_BOOST =                    5,
    FASTER_LEVITATION =              7,
    MOVEMENT_FASTER =                7,
    STRONG_KICK =                    8,
    TELEKINESIS =                   12,
    REPELLING_CAPE =                 4,
    EXPLODING_CORPSES =              5,
    SAVING_GRACE =                  12,
    INVISIBILITY =                  13,
    GLOBAL_GORE =                    9,
    REMOVE_FOG_OF_WAR =             10,
    LEVITATION_TRAIL =               7,
    VAMPIRISM =                     13,
    EXTRA_HP =                       4,
    HEARTS_MORE_EXTRA_HP =           4,
    GLASS_CANNON =                   3,
    LOW_HP_DAMAGE_BOOST =            6,
    RESPAWN =                        9,
    WORM_ATTRACTOR =                10,
    RADAR_ENEMY =                   13,
    FOOD_CLOCK =                     5,
    IRON_STOMACH =                   8,
    WAND_RADAR =                    11,
    ITEM_RADAR =                     6,
    PROTECTION_FIRE =                4,
    PROTECTION_RADIOACTIVITY =       7,
    PROTECTION_EXPLOSION =           8,
    PROTECTION_MELEE =               6,
    PROTECTION_ELECTRICITY =         9,
    TELEPORTITIS =                   8,
    TELEPORTITIS_DODGE =            12,
    STAINLESS_ARMOUR =               4,
    EDIT_WANDS_EVERYWHERE =          2,
    NO_WAND_EDITING =                1,
    WAND_EXPERIMENTER =              8,
    ADVENTURER =                     6,
    PROJECTILE_HOMING =             10,
    PROJECTILE_HOMING_SHOOTER =      7,
    FREEZE_FIELD =                   9,
    FIRE_GAS =                       8,
    DISSOLVE_POWDERS =               4,
    BLEED_SLIME =                   10,
    BLEED_OIL =                      6,
    BLEED_GAS =                      8,
    SHIELD =                         9,
    REVENGE_EXPLOSION =             11,
    REVENGE_TENTACLE =              13,
    REVENGE_RATS =                  12,
    REVENGE_BULLET =                12,
    ATTACK_FOOT =                   15,
    LEGGY_FEET =                     3,
    PLAGUE_RATS =                    7,
    VOMIT_RATS =                     9,
    CORDYCEPS =                      6,
    MOLD =                           7,
    PROJECTILE_REPULSION =           8,
    FUNGAL_DISEASE =                 8,
    PROJECTILE_SLOW_FIELD =          5,
    PROJECTILE_REPULSION_SECTOR =    6,
    PROJECTILE_EATER_SECTOR =        5,
    ORBIT =                         15,
    LUKKI_MINION =                   6,
    ELECTRICITY =                   12,
    ATTRACT_ITEMS =                  5,
    LOWER_SPREAD =                   4,
    LOW_RECOIL =                     7,
    BOUNCE =                         8,
    FAST_PROJECTILES =               7,
    ALWAYS_CAST =                    9,
    EXTRA_MANA =                     8,
    NO_MORE_KNOCKBACK =              7,
    DUPLICATE_PROJECTILE =          14,
    FASTER_WANDS =                   5,
    EXTRA_SLOTS =                    6,
    CONTACT_DAMAGE =                13,
    PERKS_LOTTERY =                  7,
    GAMBLE =                         8,
    GENOME_MORE_HATRED =             5,
    GENOME_MORE_LOVE =               5,
    MANA_FROM_KILLS =                8,
    ANGRY_LEVITATION =               6,
    PERSONAL_LASER =                12,
}